In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt

In [55]:
from dateutil import parser

In [61]:
file_path = 'RAW_DATA/Sales_data/superstore.csv'
try:
    df = pd.read_csv(file_path, parse_dates=['Order Date','Ship Date'])
    print("Data loaded successfully")
    print(f"Data Size: {df.shape}")

except FileNotFoundError:
    print("File not found")

Data loaded successfully
Data Size: (9800, 18)

In [68]:
df.head(3)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Delivery Days
0,1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,3
1,2,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3
2,3,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,4

In [67]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   str
 2   Order Date     9800 non-null   datetime64[us]
 3   Ship Date      9800 non-null   datetime64[us]
 4   Ship Mode      9800 non-null   str
 5   Customer ID    9800 non-null   str
 6   Customer Name  9800 non-null   str
 7   Segment        9800 non-null   str
 8   Country        9800 non-null   str
 9   City           9800 non-null   str
 10  State          9800 non-null   str
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   str
 13  Product ID     9800 non-null   str
 14  Category       9800 non-null   str
 15  Sub-Category   9800 non-null   str
 16  Product Name   9800 non-null   str
 17  Sales          9800 non-null   float64
 18  Delivery Days  9800 non-null   int64
dtypes: datetime64[us](2), float64(2), int64(2), str(13)
memory usage: 1.4 MB

In [52]:
# df['Order Date'] = pd.to_datetime(df['Order Date'],format='%d/%m/%Y',errors='coerce')
# df['Ship Date'] = pd.to_datetime(df['Ship Date'],format='%d/%m/%Y',errors='coerce')

In [63]:
def clean_date(date_str):
    try:
        return parser.parse(str(date_str),dayfirst=True)
    except:
        return pd.NaT

In [64]:
df['Order Date'] = df['Order Date'].apply(clean_date)
df['Ship Date'] = df['Ship Date'].apply(clean_date)

In [65]:
df['Order Date'].head()

0   2017-11-08
1   2017-11-08
2   2017-06-12
3   2016-10-11
4   2016-10-11
Name: Order Date, dtype: datetime64[us]

In [66]:
df['Delivery Days'] = (df['Ship Date'] - df['Order Date']).dt.days
df['Delivery Days'].head()

0    3
1    3
2    4
3    7
4    7
Name: Delivery Days, dtype: int64

In [69]:
df['Sales'] = pd.to_numeric(df['Sales'], errors='coerce')

np.random.seed(42)

cost_ratios = np.random.uniform(0.70, 0.90, df.shape[0])
df['Cost'] = df['Sales'] * cost_ratios

loss_mask = np.random.choice([True, False], size=df.shape[0], p=[0.1, 0.9])
df.loc[loss_mask, 'Cost'] = df['Sales'] * 1.25

df['Profit'] = df['Sales'] - df['Cost']

df['Sales'] = df['Sales'].round(2)
df['Cost'] = df['Cost'].round(2)
df['Profit'] = df['Profit'].round(2)

display(df[['Order Date', 'Sales', 'Cost', 'Profit']].head(10))

  Order Date   Sales    Cost  Profit
0 2017-11-08  261.96  202.99   58.97
1 2017-11-08  731.94  651.53   80.41
2 2017-06-12   14.62   12.37    2.25
3 2016-10-11  957.58  784.96  172.62
4 2016-10-11   22.37   16.36    6.01
5 2015-06-09   48.86   35.73   13.13
6 2015-06-09    7.28    5.18    2.10
7 2015-06-09  907.15  792.16  114.99
8 2015-06-09   18.50   15.18    3.33
9 2015-06-09  114.90   96.70   18.20

In [70]:
df.columns = df.columns.str.lower().str.replace(' ', '_').str.replace('-', '_')
df.head(3)

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,postal_code,region,product_id,category,sub_category,product_name,sales,delivery_days,cost,profit
0,1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,3,202.99,58.97
1,2,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,651.53,80.41
2,3,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,4,12.37,2.25

In [73]:
df['country'].unique().tolist()

['United States']

In [74]:
col_drop = ['row_id','country']
df.drop(columns = col_drop, inplace=True)
output_path = 'CLEANED_DATA/superstore_cleaned.csv'
df.to_csv(output_path, index=False)

In [76]:
import pandas as pd
from sqlalchemy import create_engine
engine = create_engine('mysql+pymysql://root:Uttam%239695@localhost:3306/superstore')
df.to_sql('superstore_cleaned', con=engine, if_exists='replace', index=False)
print("Data imported successfully into the database.")

Data imported successfully into the database.